"""Alembic environment.

The database URL is taken from application settings rather than alembic.ini, so
there is exactly one place that knows how to reach the database and no
connection string is ever committed.

On Streamlit Community Cloud there is no shell, so migrations are applied from a
developer machine against the hosted database as an explicit deploy step:

    alembic upgrade head
"""

from __future__ import annotations

import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

# Make the project importable when alembic is invoked from any directory.
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from modules import models  # noqa: E402,F401  (imported for its side effect:
                            #                   registering every table on Base)
from modules.config import get_settings  # noqa: E402
from modules.database import Base  # noqa: E402

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

config.set_main_option("sqlalchemy.url", get_settings().database_url)

target_metadata = Base.metadata


def _render_item(type_, obj, autogen_context):
    """Custom type rendering for autogenerated migrations.

    Two types need help:

    ``ExactNumeric``
        Autogenerate would otherwise write it as ``sa.Numeric``, and the
        migration would then create a plain NUMERIC on SQLite — reintroducing
        exactly the float conversion that ExactNumeric exists to prevent.

    ``JSON().with_variant(JSONB, "postgresql")``
        Its default repr is ``postgresql.JSONB(astext_type=Text())``, which
        references ``Text`` without importing it and makes the migration fail
        with a NameError on first run.
    """
    from sqlalchemy import JSON

    from modules.database import ExactNumeric

    if type_ != "type":
        return False

    if isinstance(obj, ExactNumeric):
        autogen_context.imports.add("from modules.database import ExactNumeric")
        return f"ExactNumeric(precision={obj.precision}, scale={obj.scale})"

    if isinstance(obj, JSON) and getattr(obj, "_variant_mapping", None):
        autogen_context.imports.add("from sqlalchemy.dialects import postgresql")
        return 'sa.JSON().with_variant(postgresql.JSONB(), "postgresql")'

    return False


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
        compare_type=True,
        compare_server_default=True,
        render_item=_render_item,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            # Batch mode rebuilds a table in order to alter it, which is the
            # only way SQLite can drop or change a column. Harmless on PostgreSQL.
            render_as_batch=True,
            compare_type=True,
            compare_server_default=True,
            render_item=_render_item,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
