"""initial schema

Revision ID: 1b94e2ecb5b1
Revises: 
Create Date: 2026-08-03 12:18:10.149800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from modules.database import ExactNumeric
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b94e2ecb5b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_key', sa.String(length=60), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_sequences')),
    sa.UniqueConstraint('scope_key', name=op.f('uq_document_sequences_scope_key'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('price_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('min_containers', sa.Integer(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_tiers')),
    sa.UniqueConstraint('code', name=op.f('uq_price_tiers_code'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('max_discount_pct', ExactNumeric(precision=9, scale=4), nullable=True),
    sa.Column('max_quote_value', ExactNumeric(precision=18, scale=2), nullable=True),
    sa.Column('min_margin_pct', ExactNumeric(precision=9, scale=4), nullable=True),
    sa.Column('can_override_warnings', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('employee_name', sa.String(length=160), nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_users_created_by_id_users')),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_users_manager_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_active', ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_app_settings_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_app_settings_key'))
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('is_customer_visible', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_attachments_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('ix_attachments_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_sha256'), ['sha256'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username_snapshot', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True),
    sa.Column('new_value_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('page', sa.String(length=80), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', ExactNumeric(precision=18, scale=8), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_exchange_rates_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchange_rates')),
    sa.UniqueConstraint('from_currency', 'to_currency', 'rate_date', name=op.f('uq_exchange_rates_from_currency_to_currency_rate_date'))
    )
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.create_index('ix_exchange_rates_lookup', ['from_currency', 'to_currency', 'rate_date'], unique=False)

    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('sheet_name', sa.String(length=120), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PREVIEWED', 'COMMITTED', 'FAILED', 'CANCELLED', name='importjobstatus', native_enum=False, length=40), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_created', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('summary_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_import_jobs_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs'))
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_number', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('size_label', sa.String(length=80), nullable=False),
    sa.Column('length_in', ExactNumeric(precision=18, scale=3), nullable=True),
    sa.Column('width_in', ExactNumeric(precision=18, scale=3), nullable=True),
    sa.Column('depth_in', ExactNumeric(precision=18, scale=3), nullable=True),
    sa.Column('flute', sa.String(length=20), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('printing_method', sa.String(length=80), nullable=True),
    sa.Column('material', sa.String(length=120), nullable=True),
    sa.Column('finish', sa.String(length=120), nullable=True),
    sa.Column('is_perforated', sa.Boolean(), nullable=True),
    sa.Column('lock_style', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_key', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_products_created_by_id_users')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_products_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('item_number', name=op.f('uq_products_item_number'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_flute'), ['flute'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_size_label'), ['size_label'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('tax_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('rate_pct', ExactNumeric(precision=9, scale=6), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_tax_rates_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_rates')),
    sa.UniqueConstraint('code', name=op.f('uq_tax_rates_code'))
    )
    with op.batch_alter_table('tax_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_rates_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('term_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('section', sa.Enum('PAYMENT_TERMS', 'QUOTATION_VALIDITY', 'LEAD_TIME', 'PRODUCTION_TIME', 'FREIGHT', 'DELIVERY_TERMS', 'INCOTERMS', 'CONTAINER_TYPE', 'LOADING_METHOD', 'CONTAINER_MIX_LIMIT', 'PRINTING', 'PRINTING_PLATE_CHARGES', 'ARTWORK_APPROVAL', 'STRUCTURAL_APPROVAL', 'RAW_MATERIAL_ADJUSTMENT', 'PURCHASE_ORDER', 'MOQ', 'OVERRUN_UNDERRUN', 'GENERAL_NOTES', name='termsection', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_term_templates_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_term_templates')),
    sa.UniqueConstraint('code', name=op.f('uq_term_templates_code'))
    )
    with op.batch_alter_table('term_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_term_templates_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('user_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('granted_by_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], name=op.f('fk_user_permissions_granted_by_id_users')),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_user_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_permissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id', name=op.f('pk_user_permissions'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_user_roles_assigned_by_id_users')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('trading_name', sa.String(length=200), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=40), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('tax_number', sa.String(length=80), nullable=True),
    sa.Column('logo_key', sa.String(length=500), nullable=True),
    sa.Column('signature_image_key', sa.String(length=500), nullable=True),
    sa.Column('signature_name', sa.String(length=160), nullable=True),
    sa.Column('signature_title', sa.String(length=120), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('default_tax_rate_id', sa.Integer(), nullable=True),
    sa.Column('default_quote_validity_days', sa.Integer(), nullable=False),
    sa.Column('quote_number_format', sa.String(length=80), nullable=False),
    sa.Column('printing_plate_rate', ExactNumeric(precision=18, scale=2), nullable=False),
    sa.Column('printing_plate_currency', sa.String(length=3), nullable=False),
    sa.Column('pdf_page_size', sa.String(length=10), nullable=False),
    sa.Column('pdf_footer_text', sa.Text(), nullable=True),
    sa.Column('pdf_confidentiality_text', sa.Text(), nullable=True),
    sa.Column('pdf_thank_you_text', sa.Text(), nullable=True),
    sa.Column('pdf_column_set', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True),
    sa.Column('pdf_show_acceptance_line', sa.Boolean(), nullable=False),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_company_settings_singleton')),
    sa.ForeignKeyConstraint(['default_tax_rate_id'], ['tax_rates.id'], name=op.f('fk_company_settings_default_tax_rate_id_tax_rates')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_company_settings_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_settings'))
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_number', sa.String(length=40), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('default_tax_rate_id', sa.Integer(), nullable=True),
    sa.Column('payment_terms', sa.String(length=200), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('assigned_sales_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PROSPECT', 'INACTIVE', 'ON_HOLD', name='customerstatus', native_enum=False, length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_sales_user_id'], ['users.id'], name=op.f('fk_customers_assigned_sales_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_customers_created_by_id_users')),
    sa.ForeignKeyConstraint(['default_tax_rate_id'], ['tax_rates.id'], name=op.f('fk_customers_default_tax_rate_id_tax_rates')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_customers_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('customer_number', name=op.f('uq_customers_customer_number'))
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_assigned_sales_user_id'), ['assigned_sales_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_item_number', sa.String(length=80), nullable=False),
    sa.Column('board_quality', sa.String(length=120), nullable=False),
    sa.Column('case_pack', sa.Integer(), nullable=False),
    sa.Column('num_colours', sa.Integer(), nullable=True),
    sa.Column('moq_packs', ExactNumeric(precision=18, scale=3), nullable=True),
    sa.Column('moq_pieces', ExactNumeric(precision=18, scale=3), nullable=True),
    sa.Column('spec_text_override', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('case_pack > 0', name=op.f('ck_product_variants_case_pack_positive')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_product_variants_created_by_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variants_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_product_variants_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('product_id', 'board_quality', 'case_pack', name=op.f('uq_product_variants_product_id_board_quality_case_pack')),
    sa.UniqueConstraint('variant_item_number', name=op.f('uq_product_variants_variant_item_number'))
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variants_board_quality'), ['board_quality'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variants_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variants_product_id'), ['product_id'], unique=False)

    op.create_table('customer_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.Enum('BILLING', 'SHIPPING', name='addresstype', native_enum=False, length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('line1', sa.String(length=200), nullable=True),
    sa.Column('line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=40), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_addresses_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_addresses'))
    )
    with op.batch_alter_table('customer_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_addresses_customer_id'), ['customer_id'], unique=False)

    op.create_table('customer_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_contacts_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_contacts'))
    )
    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_contacts_customer_id'), ['customer_id'], unique=False)

    op.create_table('import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('source_row_no', sa.Integer(), nullable=False),
    sa.Column('section_label', sa.String(length=120), nullable=True),
    sa.Column('raw_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True),
    sa.Column('normalized_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'SKIP', name='importrowaction', native_enum=False, length=40), nullable=True),
    sa.Column('status', sa.Enum('OK', 'ERROR', 'DUPLICATE', name='importrowstatus', native_enum=False, length=40), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('product_variant_id', sa.Integer(), nullable=True),
    sa.Column('created_price_ids', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], name=op.f('fk_import_rows_import_job_id_import_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_import_rows_product_variant_id_product_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_rows'))
    )
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_rows_import_job_id'), ['import_job_id'], unique=False)

    op.create_table('product_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('cost_per_pack', ExactNumeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_per_piece', ExactNumeric(precision=18, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('cost_per_pack >= 0', name=op.f('ck_product_costs_cost_non_negative')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_product_costs_created_by_id_users')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_product_costs_product_variant_id_product_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_costs')),
    sa.UniqueConstraint('product_variant_id', 'currency', 'effective_from', name=op.f('uq_product_costs_product_variant_id_currency_effective_from'))
    )
    with op.batch_alter_table('product_costs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_costs_product_variant_id'), ['product_variant_id'], unique=False)

    op.create_table('product_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('price_tier_id', sa.Integer(), nullable=False),
    sa.Column('price_per_pack', ExactNumeric(precision=18, scale=6), nullable=False),
    sa.Column('price_per_piece', ExactNumeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_workbook_name', sa.String(length=255), nullable=True),
    sa.Column('source_sheet_name', sa.String(length=120), nullable=True),
    sa.Column('source_row_no', sa.Integer(), nullable=True),
    sa.Column('import_job_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('price_per_pack > 0', name=op.f('ck_product_prices_pack_price_positive')),
    sa.CheckConstraint('price_per_piece > 0', name=op.f('ck_product_prices_piece_price_positive')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_product_prices_created_by_id_users')),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], name=op.f('fk_product_prices_import_job_id_import_jobs')),
    sa.ForeignKeyConstraint(['price_tier_id'], ['price_tiers.id'], name=op.f('fk_product_prices_price_tier_id_price_tiers')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_product_prices_product_variant_id_product_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_prices')),
    sa.UniqueConstraint('product_variant_id', 'price_tier_id', 'currency', 'effective_from', name=op.f('uq_product_prices_product_variant_id_price_tier_id_currency_effective_from'))
    )
    with op.batch_alter_table('product_prices', schema=None) as batch_op:
        batch_op.create_index('ix_product_prices_lookup', ['product_variant_id', 'price_tier_id', 'currency', 'effective_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_prices_product_variant_id'), ['product_variant_id'], unique=False)

    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_quotation_id', sa.Integer(), nullable=True),
    sa.Column('quote_number', sa.String(length=60), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('is_current_revision', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED_INTERNALLY', 'SENT_TO_CUSTOMER', 'ACCEPTED', 'REVISION_REQUIRED', 'LOST', 'EXPIRED', 'CANCELLED', name='quotationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_contact_id', sa.Integer(), nullable=True),
    sa.Column('customer_name_snapshot', sa.String(length=200), nullable=True),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=60), nullable=True),
    sa.Column('billing_address_text', sa.Text(), nullable=True),
    sa.Column('shipping_address_text', sa.Text(), nullable=True),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('brand', sa.String(length=160), nullable=True),
    sa.Column('distributor', sa.String(length=160), nullable=True),
    sa.Column('customer_po_ref', sa.String(length=120), nullable=True),
    sa.Column('sales_user_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', ExactNumeric(precision=18, scale=8), nullable=False),
    sa.Column('quote_discount_pct', ExactNumeric(precision=9, scale=4), nullable=False),
    sa.Column('quote_discount_amount', ExactNumeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_rate_id', sa.Integer(), nullable=True),
    sa.Column('tax_rate_pct', ExactNumeric(precision=9, scale=6), nullable=False),
    sa.Column('subtotal', ExactNumeric(precision=18, scale=2), nullable=False),
    sa.Column('charges_total', ExactNumeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', ExactNumeric(precision=18, scale=2), nullable=False),
    sa.Column('grand_total', ExactNumeric(precision=18, scale=2), nullable=False),
    sa.Column('total_cost', ExactNumeric(precision=18, scale=2), nullable=True),
    sa.Column('gross_profit', ExactNumeric(precision=18, scale=2), nullable=True),
    sa.Column('gross_margin_pct', ExactNumeric(precision=9, scale=4), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('revision_no >= 0', name=op.f('ck_quotations_revision_non_negative')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_quotations_created_by_id_users')),
    sa.ForeignKeyConstraint(['customer_contact_id'], ['customer_contacts.id'], name=op.f('fk_quotations_customer_contact_id_customer_contacts')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_quotations_customer_id_customers')),
    sa.ForeignKeyConstraint(['root_quotation_id'], ['quotations.id'], name=op.f('fk_quotations_root_quotation_id_quotations')),
    sa.ForeignKeyConstraint(['sales_user_id'], ['users.id'], name=op.f('fk_quotations_sales_user_id_users')),
    sa.ForeignKeyConstraint(['tax_rate_id'], ['tax_rates.id'], name=op.f('fk_quotations_tax_rate_id_tax_rates')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_quotations_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotations')),
    sa.UniqueConstraint('quote_number', 'revision_no', name=op.f('uq_quotations_quote_number_revision_no'))
    )
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_index('ix_quotations_current', ['is_current_revision', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_project_name'), ['project_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_quote_number'), ['quote_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_root_quotation_id'), ['root_quotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_sales_user_id'), ['sales_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_status'), ['status'], unique=False)
        batch_op.create_index('ix_quotations_status_date', ['status', 'quote_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_valid_until'), ['valid_until'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('triggered_rules_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'RETURNED_FOR_REVISION', name='approvaldecision', native_enum=False, length=40), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('fk_approvals_approver_id_users')),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_approvals_quotation_id_quotations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_approvals_requested_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_approver_id'), ['approver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('customer_response_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('date_sent', sa.Date(), nullable=True),
    sa.Column('sent_by_id', sa.Integer(), nullable=True),
    sa.Column('send_method', sa.Enum('EMAIL', 'COURIER', 'IN_PERSON', 'PORTAL_UPLOAD', 'OTHER', name='sendmethod', native_enum=False, length=40), nullable=True),
    sa.Column('customer_contact_id', sa.Integer(), nullable=True),
    sa.Column('response', sa.Enum('NO_RESPONSE', 'ACCEPTED', 'REVISION_REQUESTED', 'LOST', name='customerresponse', native_enum=False, length=40), nullable=False),
    sa.Column('response_date', sa.Date(), nullable=True),
    sa.Column('loss_reason', sa.Text(), nullable=True),
    sa.Column('competitor', sa.String(length=160), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_customer_response_logs_created_by_id_users')),
    sa.ForeignKeyConstraint(['customer_contact_id'], ['customer_contacts.id'], name=op.f('fk_customer_response_logs_customer_contact_id_customer_contacts')),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_customer_response_logs_quotation_id_quotations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by_id'], ['users.id'], name=op.f('fk_customer_response_logs_sent_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_response_logs'))
    )
    with op.batch_alter_table('customer_response_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_response_logs_follow_up_date'), ['follow_up_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_response_logs_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('quotation_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('charge_type', sa.Enum('PRINTING_PLATES', 'CUTTING_DIES', 'TOOLING', 'ARTWORK', 'SETUP', 'FREIGHT', 'BROKERAGE', 'DUTY', 'PALLETS', 'SAMPLES', 'RUSH_PRODUCTION', 'FUEL_SURCHARGE', 'OTHER', name='chargetype', native_enum=False, length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity_value', ExactNumeric(precision=18, scale=3), nullable=False),
    sa.Column('rate', ExactNumeric(precision=18, scale=2), nullable=False),
    sa.Column('amount', ExactNumeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', ExactNumeric(precision=18, scale=8), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('is_customer_visible', sa.Boolean(), nullable=False),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_quotation_charges_quotation_id_quotations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_charges'))
    )
    with op.batch_alter_table('quotation_charges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_charges_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('quotation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=True),
    sa.Column('product_price_id', sa.Integer(), nullable=True),
    sa.Column('is_custom_product', sa.Boolean(), nullable=False),
    sa.Column('custom_description', sa.Text(), nullable=True),
    sa.Column('description_override', sa.Text(), nullable=True),
    sa.Column('spec_text_override', sa.Text(), nullable=True),
    sa.Column('item_number_snapshot', sa.String(length=80), nullable=True),
    sa.Column('size_label', sa.String(length=80), nullable=True),
    sa.Column('depth_in', ExactNumeric(precision=18, scale=3), nullable=True),
    sa.Column('flute', sa.String(length=20), nullable=True),
    sa.Column('board_quality', sa.String(length=120), nullable=True),
    sa.Column('case_pack', sa.Integer(), nullable=True),
    sa.Column('printing_method', sa.String(length=80), nullable=True),
    sa.Column('num_colours', sa.Integer(), nullable=True),
    sa.Column('moq_packs', ExactNumeric(precision=18, scale=3), nullable=True),
    sa.Column('price_tier_id', sa.Integer(), nullable=True),
    sa.Column('pricing_basis', sa.Enum('PACK', 'PIECE', name='pricingbasis', native_enum=False, length=40), nullable=False),
    sa.Column('quantity_packs', ExactNumeric(precision=18, scale=3), nullable=False),
    sa.Column('quantity_pieces', ExactNumeric(precision=18, scale=3), nullable=False),
    sa.Column('container_count', ExactNumeric(precision=18, scale=3), nullable=False),
    sa.Column('price_per_pack', ExactNumeric(precision=18, scale=6), nullable=False),
    sa.Column('price_per_piece', ExactNumeric(precision=18, scale=6), nullable=False),
    sa.Column('is_custom_price', sa.Boolean(), nullable=False),
    sa.Column('custom_price_reason', sa.Text(), nullable=True),
    sa.Column('line_discount_pct', ExactNumeric(precision=9, scale=4), nullable=False),
    sa.Column('line_discount_amount', ExactNumeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_line_total', ExactNumeric(precision=18, scale=2), nullable=False),
    sa.Column('net_line_total', ExactNumeric(precision=18, scale=2), nullable=False),
    sa.Column('unit_cost_per_pack', ExactNumeric(precision=18, scale=6), nullable=True),
    sa.Column('line_cost_total', ExactNumeric(precision=18, scale=2), nullable=True),
    sa.Column('customer_remarks', sa.Text(), nullable=True),
    sa.Column('internal_remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity_packs >= 0', name=op.f('ck_quotation_items_qty_packs_non_negative')),
    sa.CheckConstraint('quantity_pieces >= 0', name=op.f('ck_quotation_items_qty_pieces_non_negative')),
    sa.ForeignKeyConstraint(['price_tier_id'], ['price_tiers.id'], name=op.f('fk_quotation_items_price_tier_id_price_tiers')),
    sa.ForeignKeyConstraint(['product_price_id'], ['product_prices.id'], name=op.f('fk_quotation_items_product_price_id_product_prices')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_quotation_items_product_variant_id_product_variants')),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_quotation_items_quotation_id_quotations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_items')),
    sa.UniqueConstraint('quotation_id', 'line_no', name=op.f('uq_quotation_items_quotation_id_line_no'))
    )
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_items_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('quotation_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_quotation_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('previous_snapshot_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True),
    sa.Column('previous_total', ExactNumeric(precision=18, scale=2), nullable=True),
    sa.Column('new_total', ExactNumeric(precision=18, scale=2), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('previous_pdf_attachment_id', sa.Integer(), nullable=True),
    sa.Column('new_pdf_attachment_id', sa.Integer(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_quotation_revisions_changed_by_id_users')),
    sa.ForeignKeyConstraint(['new_pdf_attachment_id'], ['attachments.id'], name=op.f('fk_quotation_revisions_new_pdf_attachment_id_attachments')),
    sa.ForeignKeyConstraint(['previous_pdf_attachment_id'], ['attachments.id'], name=op.f('fk_quotation_revisions_previous_pdf_attachment_id_attachments')),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_quotation_revisions_quotation_id_quotations')),
    sa.ForeignKeyConstraint(['root_quotation_id'], ['quotations.id'], name=op.f('fk_quotation_revisions_root_quotation_id_quotations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_revisions')),
    sa.UniqueConstraint('root_quotation_id', 'revision_no', name=op.f('uq_quotation_revisions_root_quotation_id_revision_no'))
    )
    with op.batch_alter_table('quotation_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_revisions_root_quotation_id'), ['root_quotation_id'], unique=False)

    op.create_table('quotation_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('term_template_id', sa.Integer(), nullable=True),
    sa.Column('section', sa.Enum('PAYMENT_TERMS', 'QUOTATION_VALIDITY', 'LEAD_TIME', 'PRODUCTION_TIME', 'FREIGHT', 'DELIVERY_TERMS', 'INCOTERMS', 'CONTAINER_TYPE', 'LOADING_METHOD', 'CONTAINER_MIX_LIMIT', 'PRINTING', 'PRINTING_PLATE_CHARGES', 'ARTWORK_APPROVAL', 'STRUCTURAL_APPROVAL', 'RAW_MATERIAL_ADJUSTMENT', 'PURCHASE_ORDER', 'MOQ', 'OVERRUN_UNDERRUN', 'GENERAL_NOTES', name='termsection', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_customer_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_quotation_terms_quotation_id_quotations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_template_id'], ['term_templates.id'], name=op.f('fk_quotation_terms_term_template_id_term_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_terms'))
    )
    with op.batch_alter_table('quotation_terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_terms_quotation_id'), ['quotation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_terms_quotation_id'))

    op.drop_table('quotation_terms')
    with op.batch_alter_table('quotation_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_revisions_root_quotation_id'))

    op.drop_table('quotation_revisions')
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_items_quotation_id'))

    op.drop_table('quotation_items')
    with op.batch_alter_table('quotation_charges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_charges_quotation_id'))

    op.drop_table('quotation_charges')
    with op.batch_alter_table('customer_response_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_response_logs_quotation_id'))
        batch_op.drop_index(batch_op.f('ix_customer_response_logs_follow_up_date'))

    op.drop_table('customer_response_logs')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_quotation_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_approver_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotations_valid_until'))
        batch_op.drop_index('ix_quotations_status_date')
        batch_op.drop_index(batch_op.f('ix_quotations_status'))
        batch_op.drop_index(batch_op.f('ix_quotations_sales_user_id'))
        batch_op.drop_index(batch_op.f('ix_quotations_root_quotation_id'))
        batch_op.drop_index(batch_op.f('ix_quotations_quote_number'))
        batch_op.drop_index(batch_op.f('ix_quotations_project_name'))
        batch_op.drop_index(batch_op.f('ix_quotations_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_quotations_customer_id'))
        batch_op.drop_index('ix_quotations_current')

    op.drop_table('quotations')
    with op.batch_alter_table('product_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_prices_product_variant_id'))
        batch_op.drop_index('ix_product_prices_lookup')

    op.drop_table('product_prices')
    with op.batch_alter_table('product_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_costs_product_variant_id'))

    op.drop_table('product_costs')
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_rows_import_job_id'))

    op.drop_table('import_rows')
    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_contacts_customer_id'))

    op.drop_table('customer_contacts')
    with op.batch_alter_table('customer_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_addresses_customer_id'))

    op.drop_table('customer_addresses')
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variants_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_variants_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_product_variants_board_quality'))

    op.drop_table('product_variants')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_customers_company_name'))
        batch_op.drop_index(batch_op.f('ix_customers_assigned_sales_user_id'))

    op.drop_table('customers')
    op.drop_table('company_settings')
    op.drop_table('user_roles')
    op.drop_table('user_permissions')
    with op.batch_alter_table('term_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_term_templates_deleted_at'))

    op.drop_table('term_templates')
    with op.batch_alter_table('tax_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_rates_deleted_at'))

    op.drop_table('tax_rates')
    op.drop_table('role_permissions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_size_label'))
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_flute'))
        batch_op.drop_index(batch_op.f('ix_products_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_products_category'))

    op.drop_table('products')
    op.drop_table('import_jobs')
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.drop_index('ix_exchange_rates_lookup')

    op.drop_table('exchange_rates')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_sha256'))
        batch_op.drop_index('ix_attachments_entity')

    op.drop_table('attachments')
    op.drop_table('app_settings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))
        batch_op.drop_index('ix_users_active')

    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('price_tiers')
    op.drop_table('permissions')
    op.drop_table('document_sequences')
    # ### end Alembic commands ###
