"""container shipping and logistics

Revision ID: baeb1e834b6e
Revises: 1b94e2ecb5b1
Create Date: 2026-08-04 21:14:19.015593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from modules.database import ExactNumeric

# revision identifiers, used by Alembic.
revision: str = 'baeb1e834b6e'
down_revision: Union[str, Sequence[str], None] = '1b94e2ecb5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_shipping_lines_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipping_lines')),
    sa.UniqueConstraint('name', name=op.f('uq_shipping_lines_name'))
    )
    with op.batch_alter_table('shipping_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipping_lines_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('product_container_capacity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('container_size', sa.Enum('20FT', '40FT', '40FT_HC', '45FT_HC', 'CUSTOM', name='containersize', native_enum=False, length=40), nullable=False),
    sa.Column('container_type', sa.Enum('DRY', 'HIGH_CUBE', 'REFRIGERATED', 'OPEN_TOP', 'FLAT_RACK', 'CUSTOM', name='containertype', native_enum=False, length=40), nullable=False),
    sa.Column('bundles_per_container', ExactNumeric(precision=18, scale=3), nullable=False),
    sa.Column('units_per_bundle', ExactNumeric(precision=18, scale=3), nullable=True),
    sa.Column('pallets_per_container', ExactNumeric(precision=18, scale=3), nullable=True),
    sa.Column('source_workbook_name', sa.String(length=255), nullable=True),
    sa.Column('source_row_no', sa.Integer(), nullable=True),
    sa.Column('is_anomalous', sa.Boolean(), nullable=False),
    sa.Column('anomaly_note', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('bundles_per_container > 0', name=op.f('ck_product_container_capacity_bundles_positive')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_product_container_capacity_created_by_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_container_capacity_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_container_capacity')),
    sa.UniqueConstraint('product_id', 'container_size', 'container_type', name=op.f('uq_product_container_capacity_product_id_container_size_container_type'))
    )
    with op.batch_alter_table('product_container_capacity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_container_capacity_product_id'), ['product_id'], unique=False)

    op.create_table('quotation_shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('incoterm', sa.Enum('EXW', 'FCA', 'FAS', 'FOB', 'CFR', 'CIF', 'CPT', 'CIP', 'DAP', 'DPU', 'DDP', name='incoterm', native_enum=False, length=10), nullable=True),
    sa.Column('incoterm_place', sa.String(length=160), nullable=True),
    sa.Column('origin_country', sa.String(length=120), nullable=True),
    sa.Column('port_of_loading', sa.String(length=160), nullable=True),
    sa.Column('port_of_discharge', sa.String(length=160), nullable=True),
    sa.Column('final_destination', sa.String(length=160), nullable=True),
    sa.Column('freight_method', sa.Enum('INCLUDED', 'ADDED_SEPARATELY', 'INTERNAL_ONLY', name='freightmethod', native_enum=False, length=40), nullable=False),
    sa.Column('total_freight', ExactNumeric(precision=18, scale=2), nullable=False),
    sa.Column('freight_currency', sa.String(length=3), nullable=False),
    sa.Column('freight_taxable', sa.Boolean(), nullable=False),
    sa.Column('loading_method', sa.Enum('FLOOR_LOADED', 'PALLETISED', 'SLIP_SHEET', 'OTHER', name='loadingmethod', native_enum=False, length=40), nullable=True),
    sa.Column('shipping_notes', sa.Text(), nullable=True),
    sa.Column('show_on_document', sa.Boolean(), nullable=False),
    sa.Column('customer_visible_freight', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_quotation_shipments_created_by_id_users')),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_quotation_shipments_quotation_id_quotations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_quotation_shipments_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_shipments'))
    )
    with op.batch_alter_table('quotation_shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_shipments_quotation_id'), ['quotation_id'], unique=True)

    op.create_table('shipment_containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_shipment_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('shipping_line_id', sa.Integer(), nullable=True),
    sa.Column('custom_shipping_line', sa.String(length=120), nullable=True),
    sa.Column('container_size', sa.Enum('20FT', '40FT', '40FT_HC', '45FT_HC', 'CUSTOM', name='containersize', native_enum=False, length=40), nullable=False),
    sa.Column('custom_container_size', sa.String(length=60), nullable=True),
    sa.Column('container_type', sa.Enum('DRY', 'HIGH_CUBE', 'REFRIGERATED', 'OPEN_TOP', 'FLAT_RACK', 'CUSTOM', name='containertype', native_enum=False, length=40), nullable=False),
    sa.Column('custom_container_type', sa.String(length=60), nullable=True),
    sa.Column('container_count', ExactNumeric(precision=18, scale=3), nullable=False),
    sa.Column('freight_cost', ExactNumeric(precision=18, scale=2), nullable=False),
    sa.Column('freight_currency', sa.String(length=3), nullable=False),
    sa.Column('port_of_loading', sa.String(length=160), nullable=True),
    sa.Column('port_of_discharge', sa.String(length=160), nullable=True),
    sa.Column('estimated_departure', sa.Date(), nullable=True),
    sa.Column('estimated_arrival', sa.Date(), nullable=True),
    sa.Column('transit_days', sa.Integer(), nullable=True),
    sa.Column('loading_method', sa.Enum('FLOOR_LOADED', 'PALLETISED', 'SLIP_SHEET', 'OTHER', name='loadingmethod', native_enum=False, length=40), nullable=True),
    sa.Column('maximum_product_items', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('container_count > 0', name=op.f('ck_shipment_containers_container_count_positive')),
    sa.CheckConstraint('freight_cost >= 0', name=op.f('ck_shipment_containers_freight_non_negative')),
    sa.ForeignKeyConstraint(['quotation_shipment_id'], ['quotation_shipments.id'], name=op.f('fk_shipment_containers_quotation_shipment_id_quotation_shipments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipping_line_id'], ['shipping_lines.id'], name=op.f('fk_shipment_containers_shipping_line_id_shipping_lines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipment_containers'))
    )
    with op.batch_alter_table('shipment_containers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_containers_quotation_shipment_id'), ['quotation_shipment_id'], unique=False)

    op.create_table('shipment_product_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_container_id', sa.Integer(), nullable=False),
    sa.Column('quotation_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_per_container', ExactNumeric(precision=18, scale=3), nullable=False),
    sa.Column('total_allocated_quantity', ExactNumeric(precision=18, scale=3), nullable=False),
    sa.Column('bundles_per_container', ExactNumeric(precision=18, scale=3), nullable=True),
    sa.Column('pallets_per_container', ExactNumeric(precision=18, scale=3), nullable=True),
    sa.Column('cases_per_container', ExactNumeric(precision=18, scale=3), nullable=True),
    sa.Column('pieces_per_container', ExactNumeric(precision=18, scale=3), nullable=True),
    sa.Column('allocated_freight', ExactNumeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_item_id'], ['quotation_items.id'], name=op.f('fk_shipment_product_allocations_quotation_item_id_quotation_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_container_id'], ['shipment_containers.id'], name=op.f('fk_shipment_product_allocations_shipment_container_id_shipment_containers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipment_product_allocations')),
    sa.UniqueConstraint('shipment_container_id', 'quotation_item_id', name=op.f('uq_shipment_product_allocations_shipment_container_id_quotation_item_id'))
    )
    with op.batch_alter_table('shipment_product_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_product_allocations_quotation_item_id'), ['quotation_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_product_allocations_shipment_container_id'), ['shipment_container_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_product_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_product_allocations_shipment_container_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_product_allocations_quotation_item_id'))

    op.drop_table('shipment_product_allocations')
    with op.batch_alter_table('shipment_containers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_containers_quotation_shipment_id'))

    op.drop_table('shipment_containers')
    with op.batch_alter_table('quotation_shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_shipments_quotation_id'))

    op.drop_table('quotation_shipments')
    with op.batch_alter_table('product_container_capacity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_container_capacity_product_id'))

    op.drop_table('product_container_capacity')
    with op.batch_alter_table('shipping_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipping_lines_deleted_at'))

    op.drop_table('shipping_lines')
    # ### end Alembic commands ###
